# Numpy

NumPy é uma biblioteca Python que fornece uma estrutura de dados simples mas poderosa: a matriz n-dimensional. Esta é a base sobre a qual quase todo o poder do kit de ferramentas de ciência de dados Python é construído, e aprender NumPy é o primeiro passo na jornada de qualquer cientista de dados Python.

**Numpy** significa **Numerical Python** e é um pacote para cálculos numéricos baseado em objetos chamados de Arrays (matrizes).  Também serve de base para a construção de pacotes como o Pandas, muito utilizado em projetos de Data Science.

Como vimos anteriormente, em Python temos as listas que servem ao propósito de arrays, mas são lentas de processar.

A biblioteca NumPy fornece um objeto de array que é até 50x mais rápido do que as listas Python tradicionais.

O objeto array em NumPy é chamado de **ndarray**, ele fornece muitas funções de suporte que tornam o trabalho com ndarray muito fácil.

Arrays são muito freqüentemente usados na ciência dos dados, onde a velocidade e os recursos são muito importantes.

In [2]:
# instalando o Numpy

!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


Importando a biblioteca numpy

In [3]:
import numpy as np 

In [4]:
# Vamos criar um ARRAY

arr = np.array([0, 1, 2, 3])
print (arr)

[0 1 2 3]


In [5]:
type(arr)

numpy.ndarray

Exemplos de usos de um array:

matrizes contendo:
* valores de um experimento/simulação em tempos discretos;
* sinal gravado por um equipamento de medição, por exemplo, ondas sonoras;
* pixels de uma imagem, escala de cinza ou coloridos;

In [6]:
# Criando arrays Unidimensionais

a = np.array([0, 1, 2, 3])
print(f"array: {a}")
print(f"Dimensões do array: {a.ndim}")
print(f"Forma do array: {a.shape}")

array: [0 1 2 3]
Dimensões do array: 1
Forma do array: (4,)


In [7]:
# Criando arrays Bidimensionais

b = np.array([[0, 1, 2], [3, 4, 5]])    # 2 x 3 array
print(f"array: {b}")
print(f"Dimensões do array: {b.ndim}")
print(f"Forma do array: {b.shape}")

array: [[0 1 2]
 [3 4 5]]
Dimensões do array: 2
Forma do array: (2, 3)


In [8]:
# Criando arrays espaçados igualmente

a = np.arange(10) # 0 .. n-1
print(a)
b = np.arange(1, 9, 2) # início, fim (exclusive), passo
print(b)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]


In [9]:
#Criando arrays por quantidade de pontos

c = np.linspace(0, 1, 5)   # início, fim, número de pontos
print(c)
d = np.linspace(0, 1, 5, endpoint=False)
print(d)

[0.   0.25 0.5  0.75 1.  ]
[0.  0.2 0.4 0.6 0.8]


In [10]:
#Matriz de "uns"
a = np.ones((3, 3))  # lembrete: (3, 3) é uma tupla
print(a, "\n")

#Matriz de zeros
b = np.zeros((2, 2))
print(b,"\n")

#Matriz Identidade
c = np.eye(3)
print(c, "\n")

#Matriz Digonal
d = np.diag(np.array([1, 2, 3, 4]))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[0. 0.]
 [0. 0.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


Identificando os Tipos de Dados de um array

In [11]:
a = np.array([1, 2, 3])
print(a.dtype)

b = np.array([1., 2., 3.])
print(b.dtype)

int64
float64


In [12]:
type(a) # identifica o objeto array

numpy.ndarray

In [13]:
#Especificando o tipo de dado desejado

lista = [1, 6, 2, 3, 5, 4]
a_lista = np.array(lista, dtype="float")
print(a_lista.dtype)

float64


In [14]:
a_lista

array([1., 6., 2., 3., 5., 4.])

In [15]:
a_lista.shape  # retorna uma tupla com as dimensões do array

(6,)

In [16]:
a_lista.max(axis=0)  # retorna o valor máximo no eixo designado

6.0

In [17]:
#Modificando a estrutura de um array

a_lista = a_lista.reshape(2,3)
a_lista

array([[1., 6., 2.],
       [3., 5., 4.]])

In [18]:
a_lista.max(axis=1)  #eixo 1 ---> colunas

array([6., 5.])

In [19]:
a_lista.max(axis=0)  #eixo 0 ---> linhas

array([3., 6., 4.])

In [20]:
a_lista.sum()

21.0

In [21]:
a_lista.sum(axis=0)

array([ 4., 11.,  6.])

In [22]:
a_lista.sum(axis=1)

array([ 9., 12.])

In [23]:
esticado = a_lista.flatten()
esticado

array([1., 6., 2., 3., 5., 4.])

In [24]:
esticado.reshape(6, 1)

array([[1.],
       [6.],
       [2.],
       [3.],
       [5.],
       [4.]])

In [25]:
esticado.reshape(2, -1) #colocamos o -1 para que o numpy encontre o melhor arranjo

array([[1., 6., 2.],
       [3., 5., 4.]])

In [30]:
esticado.reshape(-1, 2)

array([[1., 6.],
       [2., 3.],
       [5., 4.]])

In [32]:
# Sorting

arr = np.array([3, 2, 0, 1])

np.sort(arr)

array([0, 1, 2, 3])

In [33]:
#Sorting Strings

arr = np.array(['banana', 'cherry', 'apple'])

np.sort(arr)

array(['apple', 'banana', 'cherry'], dtype='<U6')

In [34]:
# CONCATENATE

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [35]:
# CONCATENATE

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [44]:
arr.mean()

4.5

In [45]:
np.median(arr)

4.5

* Funções universais

**numpy.randn( )**

In [47]:
# Retorna um array nas dimensões indicadas com distribuição normal (média=0, variância =1)

np.random.randn(3, 4)  

array([[ 1.31161446, -0.08813292, -1.79524034, -0.04069715],
       [-0.46815297,  0.51084933,  1.18263333, -1.0003261 ],
       [ 0.42385272, -1.10741424, -1.17561094,  0.34874484]])

**numpy.rand( )**

In [48]:
# Cria um array nas dimensões indicadas com uma distribuição uniforme no intervalo [0, 1).

np.random.rand(3, 4) 

array([[0.9839535 , 0.31428824, 0.6133556 , 0.79414641],
       [0.95398136, 0.77907159, 0.38552405, 0.18948407],
       [0.97838376, 0.55755775, 0.5678595 , 0.13348199]])

**randint( )**

In [50]:
# Retorna inteiro aletório no intervalo indicado: inferior(inclusivo) até superior (exclusivo)

np.random.randint(1,10) 

5

In [55]:
# Aqui, definimos o tamanho do array que queremos retornar com números aleatórios. Os dois primeiros números
#indicam o intervalo desejado

np.random.randint(5,15, size=(2, 4)) 

array([[10, 11, 14,  6],
       [ 9,  5, 11,  5]])

In [57]:
# O primeiro argumento define o valor máximo (exclusivo) de cada elemento para a criação do array

np.random.randint(5, size=10)

array([0, 1, 1, 0, 4, 2, 3, 4, 1, 2])

## Indexing & Slicing

In [58]:
a = np.arange(10)  # arange() no Numpy!!!
print(a, "\n")
print(a[0])
print(a[2])
print(a[-1])

[0 1 2 3 4 5 6 7 8 9] 

0
2
9


Note que:

* Em 2D, a primeira dimensão corresponde às linhas e a segunda às colunas;
* Para o array multidimensional a, a[0] é interpretado pegando-se todos os elementos da dimensão não especificada.

### Slicing

Como acontece com qualquer sequência do Python, arrays também podem ser cortadas (slicing)

* **Lembrem-se que  indexação em Python começa em 0**

Slicing em python significa retirar elementos de uma estrutura de dados (lista, array, dataframe, tupla, set)

* Passamos a fatia (slice), ao invés do índice desta forma: [start:end]

* Também podemos definir o step desta forma: [start:end:step].

* Se não passarmos o início, o default é 0

* Se não passarmos o final, o tamanho do array é o default

* Se não passarmos o step, o valor 1 é o default

**Atenção: O resultado INCLUI o start index, mas EXCLUI o end index**

In [59]:
a = np.arange(10)*2  # criamos o array
print(a, "\n")

[ 0  2  4  6  8 10 12 14 16 18] 



In [60]:
# Extraindo elementos pelo índice (index)

print(a[0])
print(a[1])
print(a[2])
print(a[8])
print(a[9])

0
2
4
16
18


In [61]:
# Slicing

a[0:9] 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [62]:
a[2:]

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [63]:
a[2:9:2]    # [início:fim:incremento]

array([ 4,  8, 12, 16])

In [64]:
a[:4] # do início (:) até o elemento anterior ao index 4

array([0, 2, 4, 6])

In [65]:
a[1:3]

array([2, 4])

In [67]:
a[:] # do início ao fim do array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [70]:
a[::2] # do início ao fim do array com passo de 2

array([ 0,  4,  8, 12, 16])

In [71]:
novo_arr = a[3:]  

In [72]:
novo_arr


array([ 6,  8, 10, 12, 14, 16, 18])

Atenção!!! Uma operação de corte cria uma visualização do array original, a qual é apenas uma forma de se acessar dos dados da array. Assim, a matriz original não é copiada na memória.

### Mais um pouquinho de Slicing: 2-D Arrays

### Exemplo: 

Do segundo elemento, fatie os elementos do índice 1 ao índice 4 (não incluído):



In [73]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr, "\n")

print(arr[1, 1:4])  #lembre que o segundo elemento possui índice 1

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

[7 8 9]


In [74]:
matriz = np.array([[1,2,3],[6,5,4],[8,7,9]])
matriz

array([[1, 2, 3],
       [6, 5, 4],
       [8, 7, 9]])

In [76]:
matriz[:]

array([[1, 2, 3],
       [6, 5, 4],
       [8, 7, 9]])

In [77]:
matriz[0, 1]  # da linha de índice 0, pegue o elemento de índice 1, ou seja, da coluna 1

2

In [78]:
matriz[[0, 1], 1] # das linhas 0 e 1, pegue os elementos da coluna 1

array([2, 5])

In [79]:
matriz[0:2, 1]  # da linha de indice 0 até a linha de indice 2, pegue os elementos da coluna 1

array([2, 5])

In [80]:
matriz[0:2, 0:2] # da linha de indice 0 até a linha de indice 2, pegue os elementos da coluna de indice 0 até a coluna de indice 2

array([[1, 2],
       [6, 5]])

In [81]:
matriz[:, 2:]

array([[3],
       [4],
       [9]])

* Operações com Ndarray

In [84]:
[1,2,3,4] * 5   # lista

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [85]:
np.array([1,2,3,4]) * 5    # ARRAY

array([ 5, 10, 15, 20])

In [86]:
np.array([1,2,3,4]) + 5

array([6, 7, 8, 9])

In [95]:
a = np.arange(8).reshape(4,-1)
b = np.arange(8).reshape(4,-1)
a + b

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])